DELIMITER $$
DROP EVENT IF EXISTS `palio_lite_qiosk`.`POST_RANDOM_SCORE` $$
CREATE EVENT `palio_lite_qiosk`.`POST_RANDOM_SCORE` ON SCHEDULE
EVERY 10 MINUTE
DO
BEGIN
UPDATE palio_lite_qiosk.POST SET `SCORE` = FLOOR(RAND( ) * 10000) WHERE `POST_ID` NOT IN ('');
UPDATE palio_lite_qiosk.PRODUCT SET `SCORE` = FLOOR(RAND( ) * 10000) WHERE `CODE` NOT IN ('');
END $$
DELIMITER ;